# Generated by Django 4.0.5 on 2022-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Person name')),
                ('Person_address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Person address')),
                ('Person_pri_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Person pri_phone')),
                ('Person_sec_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Person sec_phone')),
                ('Person_dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('Person_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('Person_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('Person_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='health status')),
                ('Person_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='health notes')),
                ('Person_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default=5, max_length=1, verbose_name='Rating')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
