# Generated by Django 4.0.5 on 2022-06-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0003_person_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOCTOR NAME')),
                ('Date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='DATE/TIME')),
                ('Health_condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='HEALTH CONDITION')),
                ('Appointment_time_duration', models.IntegerField(blank=True, null=True, verbose_name='APPOINTMENT TIME DURATION')),
                ('Appointment_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='APPOINTMENT NOTES')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid', models.IntegerField(blank=True, null=True, verbose_name='PAID')),
                ('Pending', models.IntegerField(blank=True, null=True, verbose_name='PENDING')),
                ('Invoice_id', models.IntegerField(blank=True, null=True, verbose_name='INVOICE ID')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Fees_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cunsultancy_fees', models.IntegerField(blank=True, null=True, verbose_name='CUNSULTANCY FEES')),
                ('Laboratory_fees', models.IntegerField(blank=True, null=True, verbose_name='LABORATORY FEES')),
                ('Pharmacy_fees', models.IntegerField(blank=True, null=True, verbose_name='PHARMACY FEES')),
                ('Other_fees', models.IntegerField(blank=True, null=True, verbose_name='OTHER FEES')),
                ('Grand_total', models.IntegerField(blank=True, null=True, verbose_name='GRAND TOTAL')),
                ('Paid_through', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAID THROUGH')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOSPITAL NAME')),
                ('Hospital_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOSPITAL ADDRESS')),
                ('Contact_details', models.IntegerField(blank=True, null=True, verbose_name='CONTACT DETAILS')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='INSURANCE TYPE')),
                ('Insurance_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='INSURANCE NAME')),
                ('Valid_from', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='VALID FROM')),
                ('Valid_to', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='VALID TO')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.IntegerField(blank=True, null=True, verbose_name='INVOICE NUMBER')),
                ('Company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPANY NAME')),
                ('Invoice_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='INVOICE DATE/TIME')),
                ('Invoice_due_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='INVOICE DUE DATE/TIME')),
                ('Description', models.CharField(blank=True, max_length=200, null=True, verbose_name='DESCRIPTION')),
                ('Quality', models.IntegerField(blank=True, null=True, verbose_name='QUALITY')),
                ('Price', models.IntegerField(blank=True, null=True, verbose_name='PRICE')),
                ('Tax', models.IntegerField(blank=True, null=True, verbose_name='TAX')),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='AMOUNT')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharmacy_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHARMACY NAME')),
                ('Pharmacy_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHARMACY ADDRESS')),
                ('Pharmacy_items', models.CharField(blank=True, max_length=100, null=True, verbose_name='PHARMACY ITEMS')),
                ('Syrup', models.CharField(blank=True, max_length=100, null=True, verbose_name='SYRUP')),
                ('Syrup_cost', models.IntegerField(blank=True, null=True, verbose_name='COST')),
                ('Ointment', models.CharField(blank=True, max_length=100, null=True, verbose_name='OINTMENT')),
                ('ointment_cost', models.IntegerField(blank=True, null=True, verbose_name='OINTMENT COST')),
                ('Lotions', models.CharField(blank=True, max_length=100, null=True, verbose_name='LOTIONS')),
                ('Lotion_Cost', models.IntegerField(blank=True, null=True, verbose_name='LOTION COST')),
                ('Total_Cost', models.IntegerField(blank=True, null=True, verbose_name='TOTAL COST')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Test_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_of_measure', models.CharField(blank=True, max_length=50, null=True, verbose_name='UNIT OF MEASURE')),
                ('Normal_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='NORMAL RANGE')),
                ('Result_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='RESULT VALUE')),
                ('X_ray', models.ImageField(blank=True, null=True, upload_to='x_ray/')),
                ('Result_report', models.ImageField(blank=True, null=True, upload_to='test_result')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='Added_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY'),
        ),
        migrations.AddField(
            model_name='person',
            name='Added_date_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_date_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Person_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Person_rating',
            field=models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Person_status',
            field=models.CharField(blank=True, choices=[('DEAD', 'Dead'), ('SICK', 'sick'), ('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy')], default='HEALTHY', max_length=10, null=True, verbose_name='health status'),
        ),
        migrations.CreateModel(
            name='Doctor_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialized_of', models.CharField(choices=[('1', 'CARDIOLOGIST'), ('2', 'AUDIOLOGIST'), ('3', 'DENTIST'), ('4', 'ENT SPECIALIST'), ('5', 'GYNAECOLOGIS'), ('6', 'ORTHOPAEDIC SURGEON'), ('7', 'paediatrician'), ('8', 'NEUROLOGIST')], default='select', max_length=100, verbose_name='SPECIALIZED OF')),
                ('E_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email ')),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
                ('Doctor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.appointment', verbose_name='DOCTOR NAME')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Person_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.person', verbose_name='PERSON NAME'),
        ),
    ]
