# Generated by Django 4.0.5 on 2022-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0003_person_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='TEST NAME')),
                ('Test_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST DESCRIPTION')),
                ('Test_pre_condition', models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST PRE-CONDITION')),
                ('Test_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST NOTES')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
            ],
        ),
    ]
