# Generated by Django 4.0.5 on 2022-06-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0004_appointment_fees_fees_type_hospital_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratory_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='LABORATORY NAME')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='ADDRESS')),
                ('Pin_code', models.IntegerField(blank=True, null=True, verbose_name='PIN CODE')),
                ('Test', models.CharField(blank=True, max_length=100, null=True, verbose_name='TEST')),
                ('Availability', models.CharField(blank=True, max_length=100, null=True, verbose_name='AVAILABILITY')),
                ('Reffered_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='REFFERED BY')),
                ('Added_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ADDED BY')),
                ('Added_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='ADDED DATE/TIME')),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPDATED BY')),
                ('Updated_date_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='UPDATE DATE/TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Feed_back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Rating')),
                ('Description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('Person_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.person', verbose_name='PERSON NAME')),
            ],
        ),
    ]
