# Generated by Django 4.0.5 on 2022-06-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0005_hospital_test_result_test_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
