# Generated by Django 4.0.5 on 2022-06-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0008_alter_result_test_result_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_by_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='NAME OF DOC')),
                ('Name_test', models.CharField(blank=True, max_length=50, null=True, verbose_name='NAME OF TEST')),
                ('Date_test', models.CharField(blank=True, max_length=50, null=True, verbose_name='DATE OF TEST')),
                ('Date_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='RESULT DATE ')),
                ('Prescribed_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRESCRIBED DATE ')),
                ('Description', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRESCRIBED DATE ')),
            ],
        ),
    ]
