# Generated by Django 4.0.5 on 2022-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0010_alter_health_test_date_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_type',
            name='Cunsultancy_fees',
            field=models.IntegerField(blank=True, null=True, verbose_name='CONSULTANCY FEES'),
        ),
    ]
