# Generated by Django 4.0.5 on 2022-08-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0011_alter_fees_type_cunsultancy_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Person_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PERSON NAME'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.doctor_detail', verbose_name='DOCTER NAME'),
        ),
        migrations.AlterField(
            model_name='doctor_detail',
            name='Doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOCTER'),
        ),
        migrations.AlterField(
            model_name='health_test',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DESCRIPTION'),
        ),
    ]
