# Generated by Django 4.0.5 on 2022-08-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0012_remove_appointment_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.person', verbose_name='DOCTER NAME'),
        ),
    ]
