# Generated by Django 4.0.5 on 2022-08-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0016_alter_doctor_detail_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Docter_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.doctor_detail', verbose_name='DOCTER NAME'),
        ),
    ]
