# Generated by Django 4.0.5 on 2022-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0020_alter_pharmacy_pharmacy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_type',
            name='Other_fees_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='OTHER FEES DESCRIPTION'),
        ),
    ]
