# Generated by Django 4.0.5 on 2022-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0021_fees_type_other_fees_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='Person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PERSON NAME'),
        ),
    ]
