# Generated by Django 4.0.5 on 2022-08-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0023_fees_type_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_test',
            name='Person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PERSON NAME'),
        ),
        migrations.AlterField(
            model_name='health_test',
            name='Ref_by_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='htapp.doctor_detail', verbose_name='REF BY DOC'),
        ),
    ]
