# Generated by Django 4.0.5 on 2022-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0024_health_test_person_name_alter_health_test_ref_by_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Contact_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CONTACT DETAILS'),
        ),
    ]
