# Generated by Django 4.0.5 on 2022-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0025_alter_hospital_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Hospital_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
    ]
