# Generated by Django 4.0.5 on 2022-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0026_hospital_hospital_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PERSON NAME'),
        ),
    ]
