# Generated by Django 4.0.5 on 2022-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0027_invoice_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='Pin_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='PIN CODE'),
        ),
    ]
