# Generated by Django 4.0.5 on 2022-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0029_alter_laboratory_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_time_duration',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='APPOINTMENT TIME DURATION'),
        ),
    ]
