# Generated by Django 4.0.5 on 2022-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0032_alter_appointment_appointment_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_time_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='APPOINTMENT TIME DURATION'),
        ),
    ]
