# Generated by Django 4.0.5 on 2022-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0034_rename_appointment_time_duration_appointment_appointment_time_dur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_time_dur',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_time_duration',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='APPOINTMENT TIME DURATION'),
        ),
    ]
