# Generated by Django 4.0.5 on 2022-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0035_remove_appointment_appointment_time_dur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_time_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='APPOINTMENT TIME DURATION'),
        ),
    ]
