# Generated by Django 4.0.5 on 2022-08-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0036_alter_appointment_appointment_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name=' NEED ON DATE/TIME'),
        ),
    ]
