# Generated by Django 4.0.5 on 2022-08-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0037_alter_appointment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_time_duration',
        ),
    ]
