# Generated by Django 4.0.5 on 2022-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0038_remove_appointment_appointment_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Person_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Personal EMAIL'),
        ),
    ]
