# Generated by Django 4.0.5 on 2022-08-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0039_appointment_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Person_email',
        ),
    ]
