# Generated by Django 4.0.5 on 2022-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0040_remove_appointment_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='Pharmacy_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MACY ITEMS'),
        ),
    ]
