# Generated by Django 4.0.5 on 2022-08-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0041_pharmacy_pharmacy_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='Pharmacy_item',
        ),
    ]
