# Generated by Django 4.0.5 on 2022-08-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htapp', '0043_appointment_appointment_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_duration',
        ),
    ]
